#define PACKAGE_NAME "pfstmo"
#define PACKAGE_TARNAME "pfstmo"
#define PACKAGE_VERSION "1.4"
#define PACKAGE_STRING "pfstmo 1.4"
#define PACKAGE_BUGREPORT "rafm@users.sourceforge.net"
#define PACKAGE "pfstmo"
#define VERSION "1.4"
